version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: tdvwork696/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: tdvwork696/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: tdvwork696/foodgram_gateway  
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
